export const SELECTORS = {
    // Login Page
    LOGIN: {
        USERNAME_INPUT: '//*[@resource-id="Login.userName-TextInput.input-field"]',
        PASSWORD_INPUT: '//*[@resource-id="Login.password-TextInput.input-field"]',
        LOGIN_BUTTON: '//*[@resource-id="Login.ButtonMain.text"]',
        ERROR_MESSAGE: '//android.widget.TextView[@resource-id="errorMessage"]',
        UNDERSTOOD_BUTTON: '~הבנתי, תודה',
        ALLOW_PERMISSION_BUTTON: 'id:com.android.permissioncontroller:id/permission_allow_button',
        USER_AGREEMENT_CHECKBOX: '//*[@resource-id="eula.Checkbox.button"]',
        CONTINUE_BUTTON: '~המשך',
        EXIT_FINGERPRINT_AUTH: '~יציאה',
        STUB_POPUP: '//*[@text="למסך הבית"]',
        STUB_MAGIC_BTN: '//*[@text="Magic"]',
        EDIT_USERS_BUTTON: '~עריכת משתמשים',
        CHANGE_USER_TEXT: '~החלפת משתמש',
        CHANGE_USER_CONTAINER: '(//android.widget.ScrollView)[last()]',
        LOGIN_WITH_OTHER_USER_BUTTON: '~התחברות עם משתמש אחר',
        LAST_ACTIONS_CONTAINER: '~פעולות מקודמות',
        LEUMI_BONUS_BUTTON: '//*[contains(@content-desc="לאומי בונוס")]',
        DATA_IN_TOUCH_BUTTON: '//*[contains(@content-desc, "נתונים")]',
        CHEKS_DEPOSIT_BUTTON: '//*[contains(@content-desc, "שיקים")]',
        MONEY_TRANSFER_BUTTON: '//*[contains(@content-desc, "העברת")]',
        MORTGAGE_REQUEST_BUTTON: '//*[contains(@content-desc, "משכנתא")]',
        LOAN_GET_BUTTON: '//*[contains(@content-desc, "הלוואה")]',
        CARDLESS_WITHDRAWAL_BUTTON: '//*[contains(@content-desc, "ללא כרטיס")]',
    },
    // Settings Page
    SETTINGS: {
        ENV_PRODUCTION: 'id:com.leumi.leumiwallet:id/setting_radio_prod',
        ENV_HB5: 'id:com.leumi.leumiwallet:id/setting_radio_hb5',
        ENV_MESIRA: 'id:com.leumi.leumiwallet:id/setting_radio_mesira',
        ENV_DEVELOPMENT: 'id:com.leumi.leumiwallet:id/setting_radio_dev',
        ENV_STUB: 'id:com.leumi.leumiwallet:id/setting_radio_stub',
        ENV_MOCKINGBIRD: 'id:com.leumi.leumiwallet:id/checkBoxMockingBirdState',
        GO_TO_APP_BUTTON: 'id:com.leumi.leumiwallet:id/go_to_app',
        CLEAR_DATA_BUTTON: 'id:com.leumi.leumiwallet:id/button_clear_data',
        BRAID_NUMBER_PICKER: 'id:com.leumi.leumiwallet:id/environment_spinner',
        BRAID_NUMBER_01: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="01"]',
        BRAID_NUMBER_02: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="02"]',
        BRAID_NUMBER_03: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="03"]',
        BRAID_NUMBER_04: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="04"]',
        BRAID_NUMBER_05: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="05"]',
        BRAID_NUMBER_06: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="06"]',
        BRAID_83BKX: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="83BKX"]',
        BRAID_83BQ8: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="83BQ8"]',
        BRAID_83BXL: '//*[@resource-id="com.leumi.leumiwallet:id/text" and @text="83BXL"]',
        BRAID_85B4A: '//android.widget.TextView[@resource-id="com.leumi.leumiwallet:id/text" and @text="85B4A"]',
        STUB_TEXT_BOX: 'id:com.leumi.leumiwallet:id/editTextLocalStubAddress'
    },
    // Home Page
    HOME_PAGE: {
        ACCOUNT_BALANCE: '//*[@resource-id="Overview.balance-text"]',

        BALANCE_IN_OTHER_BANKS_TEXT: '//*[@resource-id="amount-text"]',
        DATE_TEXT: '//*[@resource-id="Overview.date-text"]',

        LAST_ACCOUNT_TRANSACTIONS_BUTTON: '//*[@content-desc="תנועות אחרונות בחשבון"]',
        CREDIT_CARDS_BUTTON: '//*[contains(@content-desc, "כרטיסי האשראי")or contains(@content-desc, "כרטיסי אשראי")]',
        CREDIT_CARDS_BALACE_ILS_TEXT: '//*[@resource-id="Overview.CreditCards.header-nis-text"]',
        CREDIT_CARDS_BALACE_USD_TEXT: '//*[@resource-id="Overview.CreditCards.header-usd-text"]',
        FOREIGN_CURRENCY_BUTTON: '//*[contains(@content-desc, "מטבע חוץ")]',
        FOREIGN_CURRENCY_ILS_TEXT: '//*[@resource-id="Overview.ForeignAccounts.default.InnerRow.number-text"]',
        FOREIGN_DEPOSITS_BUTTON: '//*[contains(@content-desc, "הפקדונות במטבע חוץ")]',
        FOREIGN_CURRENCLY_DEPOSITS_ILS_TEXT: '//*[@resource-id="Overview.ForeignDeposits.default.InnerRow.number-text"]',
        FOREIGN_LOANS_BUTTON: '//*[contains(@content-desc,"ההלוואות במטבע חוץ") ]',
        FOREIGN_LOANS_ILS_TEXT: '//*[@resource-id="Overview.ForeignLoans.default.InnerRow.number-text"]',
        DEPOSITS_AND_SAVING_BUTTON: '//*[contains(@content-desc, "פיקדונות וחסכונות") or contains(@content-desc, "הפקדונות והחסכונות")]',
        DEPOSITS_AND_SAVING_ILS_TEXT: '//*[@resource-id="Overview.ForeignAccounts.default.InnerRow.number-text"]',
        SECURITIES_BUTTON: '//*[contains(@content-desc, "ניירות ערך")]',
        SECURITIES_ILS_TEXT: '//*[@resource-id="Overview.Security.default.InnerRow.number-text"]',
        LOANS_BUTTON: '//*[contains(@content-desc, "הלוואות")]',
        LOANS_ILS_TEXT: '//*[@resource-id="Overview.Loans.default.InnerRow.number-text"]',
        MORTGAGES_BUTTON: '//*[contains(@content-desc, "משכנתאות")]',
        MORTGAGES_ILS_TEXT: '//*[@resource-id="Overview.Mortgages.default.InnerRow.number-text"]',
        PROVIDENT_FUNDS_BUTTON: '//*[contains(@content-desc, "קופות גמל ו או קרנות השתלמות")]',
        PROVIDENT_FUNDS_ILS_TEXT: '//*[@resource-id="Overview.Provident.default.InnerRow.number-text"]',
        TRANSFERS_AND_PAYMENTS_BUTTON: '//*[@content-desc="העברות ותשלומים"]',
        MONEY_TRANSFER_BUTTON: '~העברת כסף',

        CHECKS_BUTTON: '//*[@content-desc="שיקים"]',
        GUARANTEES_BUTTON: '//*[@content-desc="ערבויות"]',
        SETTING_AND_PROFILE_BUTTON: '//*[@content-desc="הגדרות ופרופיל"]',
        MY_FINANCIAL_INFRO_BUTTON: '//*[contains(@content-desc, "המידע הפיננסי שלי")]',
        CERTIFICATE_PRODUCTION_BUTTON: '//*[@content-desc="הפקת אישורים"]',
        MORE_ACTIONS_BUTTON: '~פעולות נוספות',

        DEPOSIT_FOR_DEPOSIT_BUTTON: '//*[@content-desc="הפקדה לפיקדון"]',

        OVERVIEW_BUTTON: '//*[@resource-id="navigator.tabs.item-OVERVIEW"]',
        FEED_BUTTON: '//*[@resource-id="navigator.tabs.item-FEED"]',
        ACTIONS_BUTTON: '//*[@resource-id="navigator.tabs.item-ACTIONS"]',
        UPDATES_BUTTON: '//*[@resource-id="navigator.tabs.item-UPDATES"]',
        CONTACT_BUTTON: '//*[@resource-id="navigator.tabs.item-CONTACT_MENU"]',
        USER_DETAILS_BUTTON: '//*[@resource-id="app-header.account-selection-button"]',
        EDIT_ACCOUNT_DETAILS_BUTTON: '~עריכת פרטי חשבון',
        EDIT_ACCOUNT_DETAILS_TEXT: '~עריכת פרטי חשבון',
        BACK_BUTTON: '~סגור',
        CHOOSE_ACCOUNT_TEXT: '~בחירת חשבון',
        LOGOFF_APPLICATION_BUTTON: '~התנתקות מהאפליקציה',
        DO_YOU_WANT_TO_LOGOFF_TEXT: '~האם ברצונך לצאת מהאפליקציה?',
        YES_BUTTON: '~כן',
        NO_BUTTON: '~לא',
    },
    // Money Transfer Page
    MONEY_TRANSFER: {
        CONTINUE_BUTTON: '~המשך',
        SKIP_BUTTON: '~דלג',
        UNDERSTOOD_BUTTON: '~הבנתי, תודה',
        FIRST_NAME_AND_LAST_NAME_INPUT: '//*[@resource-id="edit-text"]',
        BENEFICIARYIES_LIST_CONTAINER: '(//android.widget.ScrollView)[1]',
        BANK_BUTTON: '~לחץ לבחירת בנק ',
        SEARCH_BANK: '//*[@resource-id="search-box-edit-text"]',
        BANK_LIST_CONTAINER: '//android.widget.ScrollView[count(.//android.view.ViewGroup) >= 3 and .//*[@resource-id="search-box-edit-text"]]',
        POALIM_BANK_BUTTON: '//*[contains(@content-desc, "פועלים")]',
        BRANCH_NUMBER_BUTTON: '//*[contains(@content-desc, "מספר סניף")]',
        SEARCH_BRANCH: '//*[@resource-id="search-box-edit-text"]',
        NATANIA_BRANCH_BUTTON: '//*[@text="נתניה"]',
        ACCOUNT_NUMBER_INPUT: '//*[@resource-id="edit-text"]',
        TRANSFER_AMOUNT_INPUT: '//*[@resource-id="edit-text"]',
        TODAY_BUTTON: '//*[contains(@content-desc, "היום")]',
        FUTURE_BUTTON: '//*[contains(@content-desc, "עתידית")]',
        DIARY_BUTTON: '//*[@text="תאריך ההתחלה"]/preceding-sibling::android.widget.Button[@resource-id="accessible-rect-button" and contains(@content-desc, ".")]',
        NEXT_MONTH_BUTTON: '//*[@resource-id="android:id/next"]',
        PREV_MONTH_BUTTON: '//*[@resource-id="android:id/prev"]',
        CANCEL_BUTTON: '//*[@resource-id="android:id/button2"]',
        CONFIRM_BUTTON: '//*[@resource-id="android:id/button1"]',
        CYCLICAL_BUTTON: '//*[contains(@content-desc, "מחזורית")]',
        CYCLICAL_DROPDOWN_BUTTON: '//*[@text="כל חודש"]',
        OPTION_EVERY_MONTH: '//*[contains(@content-desc, "כל חודש")]',
        OPTION_EVERY_QUARTERLY: '//*[contains(@content-desc, "כל רבעון")]',
        OPTION_EVERY_WEEK: '//*[contains(@content-desc, "כל שנה")]',
        TRANSFER_PURPOSE_INPUT: '//*[@resource-id="edit-text"]',
        PAYMENT_OPTION: '//*[contains(@content-desc, "תשלום")]',
        SALARY_OPTION: '//*[contains(@content-desc, "משכורת")]',
        RENT_OPTION: '//*[contains(@content-desc, "שכר דירה")]',
        EVENT_OPTION: '//*[contains(@content-desc, "אירוע")]',
        HOUSE_COMMITTEE_OPTION: '//*[contains(@content-desc, "ועד בית")]',
        RETURN_MONEY_OPTION: '//*[contains(@content-desc, "להחזיר כסף")]',
        AMONG_MY_ACCOUNTS_OPTION: '//*[contains(@content-desc, "בין חשבונותיי")]',
        RELATIVE_OPTION: '//*[contains(@content-desc, "לקרוב משפחה")]',
        INCREASED_DETECTION_TITLE: '~זיהוי מוגבר',
        CONFIRM_TRANSFER_BUTTON: '~אישור וביצוע ההעברה',
        IBAN_TRANSFER_BUTTON: '~//*[contains(@content-desc,"IBAN")]',
        FOREIGN_CURRENCY_TRANSFER_BUTTON: '//*[contains(@content-desc,"העברת מטבע חוץ")]',
        TRANSFER_TO_CONTACT_BUTTON: '//*[contains(@content-desc,"העברה לאיש קשר")]',
        CARDLESS_CASH_WITHDRAWAL_BUTTON: '//*[contains(@content-desc,"משיכת מזומן ללא כרטיס")]',
        SEND_CASH_TO_CONTACT_BUTTON: '//*[contains(@content-desc,"שליחת מזומן לאיש קשר")]',
        RETURN_CHECK_PAYMENT_BUTTON: '//*[contains(@content-desc,"תשלום בצילום שובר")]',
        MANUAL_CHECK_PAYMENT_BUTTON: '//*[contains(@content-desc,"תשלום שובר באופן ידני")]',
        RELEASE_DIRECT_DEBIT_AUTHORIZATION_BUTTON: '//*[contains(@content-desc,"פתיחת הרשאה לחיוב חשבון")]',
        MANAGE_DIRECT_DEBIT_AUTHORIZATIONS_BUTTON: '//*[contains(@content-desc,"ביטול הרשאות לחיוב חשבון")]',
        MANAGE_STANDING_ORDERS_BUTTON: '//*[contains(@content-desc,"ביטול הוראות קבע")]',
        AMOUNT_FOR_CARDLESS_CASH_WITHDRAWAL_INPUT: '//*[@resource-id="edit-text"]',
        WANT_CARDLESS_MORE_BUTTON: '//*[@content-desc="רוצה למשוך יותר?"]',
        UPDATE_PHONE_NUMBER_BUTTON: '//*[@content-desc="לעדכון מספר הטלפון"]',
        SEND_CODE_IN_VOICE_MESSAGE_BUTTON: '//*[@resource-id="step02-send-code.voice-message-button.button-core.button"]',
        SEND_CODE_IN_SMS_BUTTON: '//*[@resource-id="step02-send-code.sms-button.button-core.button"]',
        LOCATING_NEARBY_ATM_BUTTON: '//*[@content-desc="לאיתור כספומט קרוב"]',
        MAKE_SURE_DETAILS_ARE_CORRECT: '//*[contains(@content-desc,"רגע לפני")]',
        FINISH_BUTTON: '~סיום',
    },
    // Deposits Page
    DEPOSITS_PAGE: {

        SKIP_BUTTON: '//*[@text="דלג"]',
        CONTINUE_BUTTON: '//*[@content-desc="המשך"]',
        RETURN_BUTTON: '~חזור',
        UNDERSTOOD_BUTTON: '~הבנתי, תודה',
        EXIT_BUTTON: '~יציאה',
        I_HAVE_MONEY_ASIDE_BUTTON: '//*[@text="יש לי כסף בצד"]',
        MONTHLY_FIXED_DEPOSIT_BUTTON: '//*[contains(@content-desc,"חסכון חודשי למטרה")]',
        SAVINGS_IN_TOUCH_BTTON: '//*[@resource-id="menu.menu-item-2-button"]',
        MONTHLY_DEPOSIT_AMOUNT_INPUT: '//android.widget.EditText[@content-desc="סכום הפקדה חודשי"]',
        FIXED_AMOUNT_OPTION: '//*[@resource-id="savingToTarget_02.radio-group.item-fixed.gradient"]',
        LINKAGE_CUNSUMER_PRICE_OPTION: '//*[@resource-id="savingToTarget_02.radio-group.item-attached.gradient"]',
        SWITCH_BUTTON: '//android.view.ViewGroup[@resource-id="savingToTarget_02.switch.Thumb.thumb"]',
        FIRST_DEPOSIT_INPUT: '//android.widget.EditText[@content-desc="הזנת סכום להפקדה ראשונית"]',
        HOW_MATCH_TO_DEPOSIT_TEXT: '//*[@text="כמה נפקיד?"]',
        AMOUNT_FOR_DEPOSIT_INPUT: '//*[@resource-id="edit-text"]',
        WHAT_YOU_PREFER_MORE_TEXT: '//*[@resource-id="moneyIsAvailable_02.carousel.slider.carousel-title"]',
        DEPOSITS_LIST_CONTAINER: '//android.widget.HorizontalScrollView',
        SEARCH_DEPOSIT_1_OF_5_BUTTON: '//*[contains(@resource-id,"step-4")]',
        SEARCH_DEPOSIT_2_OF_5_BUTTON: '//*[contains(@resource-id,"step-3")]',
        SEARCH_DEPOSIT_3_OF_5_BUTTON: '//*[contains(@resource-id,"step-2")]',
        SEARCH_DEPOSIT_4_OF_5_BUTTON: '//*[contains(@resource-id,"step-1")]',
        SEARCH_DEPOSIT_5_OF_5_BUTTON: '//*[contains(@resource-id,"step-0")]',
        AVAILABLE_MONEY_BUTTON: '//*[@content-desc="כסף זמין"]',
        HIGH_INTEREST_BUTTON: '//*[@content-desc="ריבית גבוהה"]',
        DEPOSIT_CHARACTERISTICS_BUTTON: '//*[@text="מאפייני הפיקדון"]',
        CONTINUE_THIS_DEPOSIT_BUTTON: '~המשך עם פיקדון זה',
        PRIME_30_59_DAYS_SELECT_BUTTON: `//android.view.ViewGroup[contains(@content-desc, 'שם פק"מ פריים 30-59 ימים')]/parent::android.view.ViewGroup/android.view.ViewGroup[contains(@resource-id, 'select-button')]`,
        PRIME_FOR_365_DAYS_SELECT_BUTTON: `//android.view.ViewGroup[contains(@content-desc, 'שם פק"מ פריים ל- 365 ימים')]/parent::android.view.ViewGroup/android.view.ViewGroup[contains(@resource-id, 'select-button')]`,
        SHEKEL_INDEX_CHOICE_FOR_YEAR_SELECT_BUTTON: `//android.view.ViewGroup[contains(@content-desc, 'שם ברירת שקל מדד לשנה')]/parent::android.view.ViewGroup/android.view.ViewGroup[contains(@resource-id, 'select-button')]`,

        DEPOSIT_DETAILS_BUTTON: '//*[contains(@content-desc,"לפרטי הפיקדון")]',
        DEPOSIT_SELECT_BUTTON: '//*[contains(@content-desc,"בחירה")]',
        INTEREST_FORMULA_TEXT: '//*[contains(@resource-id, "interest-formula")]',
        INTEREST_RATE_TEXT: '//*[contains(@resource-id, "saving-interest")]',
        INTEREST_LABEL_TEXT: '//*[contains(@resource-id, "repayment-interest")]',
        EXIT_POINTS_TEXT: '//*[contains(@resource-id, "exit-points")]',
        INTEREST_TYPE_TEXT: '//*[contains(@resource-id, "saving-interest-type")]',
        DEPOSIT_DURATION_TEXT: '//*[contains(@resource-id, "due-date")]',

        ABOUT_PRODUCT_BUTTON: '//*[@content-desc="על המוצר"]',
        FIRST_ROUTE_BUTTON: '//*[@content-desc="מסלול א"]',
        SECOND_ROUTE_BUTTON: '//*[@content-desc="מסלול ב"]',

        DATE_INPUT: '//android.widget.EditText[@content-desc="עריכת עד תאריך"]',
        DIARY_BUTTON: '//*[@content-desc="לחץ לפתיחת תאריכון"]',
        NEXT_MONTH_BUTTON: '//*[@resource-id="moneyIsAvailable_03.end-date-picker.date-picker.calendar.header.rightArrow"]',
        PREV_MONTH_BUTTON: '//*[@resource-id="moneyIsAvailable_03.end-date-picker.date-picker.calendar.header.leftArrow"]',
        HOW_TO_CALL_DEPOSIT_TEXT: '~איך לקרוא לפיקדון?',
        DEPOSIT_NAME_TEXT: '//android.view.ViewGroup[@content-desc="שם הפיקדון"]',
        DEPOSIT_NAME_INPUT: '//*[@resource-id="edit-text"]',
        YOU_CAN_ALSO_CHOOSE_TEXT: '//*[@text="אפשר גם לבחור"]',
        VACATION_BUTTON: '//*[contains(@content-desc, "חופשה")]',
        WEDDING_BUTTON: '//*[contains(@content-desc, "חתונה")]',
        CAR_BUTTON: '//*[contains(@content-desc, "רכב")]',
        EVENT_BUTTON: '//*[contains(@content-desc, "אירוע")]',
        HOBBIES_BUTTON: '//*[contains(@content-desc, "תחביבים")]',
        RAINY_DAY_BUTTON: '//*[contains(@content-desc, "יום גשום")]',
        FOR_DISTANT_FUTURE_BUTTON: '//*[contains(@content-desc, "לעתיד הרחוק")]',
        STUDIES_BUTTON: '//*[contains(@content-desc, "לימודים")]',
        CHOOSE_DAY_2_BUTTON: '//*[contains(@content-desc, "2")]',
        CHOOSE_DAY_10_BUTTON: '//*[contains(@content-desc, "10")]',
        CHOOSE_DAY_15_BUTTON: '//*[contains(@content-desc, "15")]',
        CHOOSE_OTHER_DAY_BUTTON: '//*[contains(@content-desc, "אחר")]',
        DAY_1_BUTTON: `~1`,
        DAY_2_BUTTON: `~2`,
        DAY_3_BUTTON: `~3`,
        DAY_4_BUTTON: `~4`,
        DAY_5_BUTTON: `~5`,
        DAY_6_BUTTON: `~6`,
        DAY_7_BUTTON: `~7`,
        DAY_8_BUTTON: `~8`,
        DAY_9_BUTTON: `~9`,
        DAY_10_BUTTON: `~10`,
        DAY_11_BUTTON: `~11`,
        DAY_12_BUTTON: `~12`,
        DAY_13_BUTTON: `~13`,
        DAY_14_BUTTON: `~14`,
        DAY_15_BUTTON: `~15`,
        DAY_16_BUTTON: `~16`,
        DAY_17_BUTTON: `~17`,
        DAY_18_BUTTON: `~18`,
        DAY_19_BUTTON: `~19`,
        DAY_20_BUTTON: `~20`,
        DAY_21_BUTTON: `~21`,
        DAY_22_BUTTON: `~22`,
        DAY_24_BUTTON: `~24`,
        DAY_25_BUTTON: `~25`,
        DAY_26_BUTTON: `~26`,
        DAY_27_BUTTON: `~27`,
        DAY_28_BUTTON: `~28`,
        DAY_29_BUTTON: `~29`,
        DAY_30_BUTTON: `~30`,
        DAY_31_BUTTON: `~31`,
        DEPOSIT_PERIOD_TEXT: '//*[contains(@text,"תקופת הפיקדון")]/following-sibling::*[contains(@text,"תאריך")]',
        ANNUAL_INTEREST_TO_PAID_TEXT: '//*[@text="ריבית שנתית לפרעון"]/following-sibling::*[contains(@text,"משתנה")]',
        AVAILABILITY_TEXT: '//*[@text="זמינות"]/following-sibling::*[contains(@text,"נקודות יציאה")]',
        CONFIRMATION_OF_DEPOSIT_DETAILS_TEXT: '~אישור פרטי הפקדה לפיקדון',
        FOR_FULL_DEPOSIT_DETAILS_BUTTON: '~לפרטי הפיקדון המלאים >',
        CONFIRMATION_BUTTON: '~אישור',
        FINISH_BUTTON: '~סיום',
    }
}
export const TIMEOUTS = {
    DEFAULT: 30000,
    QUICK: 5000
};